name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate snake graph
    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: Ajith-yash
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=dark

      - name: Upload files to GitHub Pages
        uses: ppodds/upload-to-github-pages-action@v2.0.0
        with:
          branch: output
          folder: dist

