name: Generate Snake Animation

on:
  schedule:
      - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
      branches:
        - main

jobs:
  build:
    name: Generate snake graph
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: Ajith-yash
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=dark

      - name: Upload files to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
